"""initial

Revision ID: ca69a40129a2
Revises: 
Create Date: 2023-11-26 22:20:07.212665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca69a40129a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('item', 'size',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('item', 'color',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'item', ['id'])
    op.alter_column('myuser', 'name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('myuser', 'surname',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('myuser', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('myuser', 'login',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('myuser', 'password',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('myuser', 'contact_number',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index('contact_number', table_name='myuser')
    op.drop_index('login', table_name='myuser')
    op.drop_index('password', table_name='myuser')
    op.create_unique_constraint(None, 'myuser', ['id'])
    op.alter_column('order_item', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('order_item', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('order_item', 'item_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'order_item', ['id'])
    op.drop_constraint('fk_myuser_id', 'order_item', type_='foreignkey')
    op.drop_constraint('fk_item_id', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'myuser', ['user_id'], ['id'])
    op.create_foreign_key(None, 'order_item', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('fk_item_id', 'order_item', 'item', ['item_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_myuser_id', 'order_item', 'myuser', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'order_item', type_='unique')
    op.alter_column('order_item', 'item_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order_item', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order_item', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'myuser', type_='unique')
    op.create_index('password', 'myuser', ['password'], unique=False)
    op.create_index('login', 'myuser', ['login'], unique=False)
    op.create_index('contact_number', 'myuser', ['contact_number'], unique=False)
    op.alter_column('myuser', 'contact_number',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('myuser', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('myuser', 'login',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('myuser', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('myuser', 'surname',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('myuser', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.drop_constraint(None, 'item', type_='unique')
    op.alter_column('item', 'color',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('item', 'size',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('item', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
